### ISSUE TITLE
Discount is not assigned

### ISSUE THREAD

**Issue by medoni** [mastoj/CQRSShop#1]
The parameter discount is not assigned to the local _discount field.

https://github.com/mastoj/CQRSShop/blob/8af7e28e7b4ea386a41dc0b0e2f1448334d0e0a6/src/CQRSShop.Domain/Aggregates/Basket.cs#L17

**Comment by medoni** [comment]
I have found the assignment. I'm new to event sourcing.

https://github.com/mastoj/CQRSShop/blob/8af7e28e7b4ea386a41dc0b0e2f1448334d0e0a6/src/CQRSShop.Domain/Aggregates/Basket.cs#L36

**Comment by mastoj** [comment]
@medoni. good you found it.
